workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Test step
        script: echo "Build started"

    artifacts:
      - build/**/*.ipa
